services:
  server:
    image: ghcr.io/aet-devops25/w10-template/server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://database:5432/mensa
      - LLM_SERVICE_URL=http://llm:5000
    ports:
      - "8080:8080"
    restart: unless-stopped

  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
      - POSTGRES_DB=${POSTGRES_DB:-mensa}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  client:
    image: ghcr.io/aet-devops25/w10-template/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8080/api}
    depends_on:
      - server
    restart: unless-stopped

  llm:
    image: ghcr.io/aet-devops25/w10-template/llm:latest
    build:
      context: ./llm
      dockerfile: Dockerfile
    environment:
      - CHAIR_API_KEY=${CHAIR_API_KEY:-your_api_key_here}
    ports:
      - "5000:5000"
    restart: unless-stopped




#++++++++++++++       Other materials ++++++++#




  mongo_db:
    image: mongo:8
    ports:
      # MongoDB's default port is 27017
      - "27017:27017"
    environment:
      # These variables create the root user when the database is first initialized
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-supersecret}
    volumes:
      # MongoDB stores its data in the /data/db directory inside the container
      - mongo_data:/data/db
    restart: unless-stopped



  mysql_db:

    image: mysql:9.4
    ports:
      # MySQL's default port is 3306
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mensa}
      - MYSQL_USER=${MYSQL_USER:-mysqluser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-anothersecret}
    volumes:
      # MySQL stores its data in the /var/lib/mysql directory inside the container
      - mysql_data:/var/lib/mysql
    restart: unless-stopped






  nginx:
      image: nginx:latest
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        # Mount the Nginx configuration file
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro


      depends_on:
        - server
        - client







volumes:
  mongo_data:
  db_data:
  mysql_data:










